### ISSUE TITLE
Is theme Full Screen?

### ISSUE THREAD

**Issue by neilabdev** [blocknotes/activeadmin_materialize_theme#8]
Thanks in advance for the great work. Not sure if its a bug or I installed improperlly. But shluld it be full screen, if not how would I make these changes? Please see depicted screenshot using rails 7.

![full_screen_material](https://user-images.githubusercontent.com/2140679/224579594-04ac1ab4-d486-4a4f-bba1-78b92ed861d9.png)

**Comment by neilabdev** [comment]
While I don't know if this is the proper way, this is how I achieved it :)

```css

body.active_admin #wrapper {
  max-width: 98% !important;
}

@media only screen and (min-width : 993px) {
    body.active_admin #wrapper {
    width: 98% !important;
  }
}

@media only screen and (min-width : 601px) {
  .container, body.active_admin #wrapper {
    width: 98% !important;
  }
}

```
